### ISSUE TITLE
Add rounded corners as a built-in option

### ISSUE THREAD

**Issue by carlcraig** [carlcraig/grunt-app-icons#2]
@idpaterson 

Add rounded corners as suggested in  #1

**Comment by carlcraig** [comment]
I think the rounded corners could be a cool feature to have built in to the module. Would there be a way to customize the corner radius?

**Comment by idpaterson** [comment]
I think that the easiest and most consistent way to customize the radius would be as a ratio to the image width. The example uses the iPhone ratio of 20 pixels radius to 114 pixels width. A ratio as a decimal might be a bit obscure, but it lets you specify the radius in a way that looks the same for all sizes. If documented as 

```
cornerRadiusRatio: 20 / 114
```

rather than 

```
cornerRadiusRatio: 0.175438596
```

I think the setting makes a lot more sense. Pulling it out into two settings for a corner radius and the icon width for which to use that radius (the two parts of the ratio that would just be divided internally) is likely more confusing. Another alternative of supporting an explicit corner radius for each icon size is probably excessive.

**Comment by idpaterson** [comment]
Worth mentioning that I tried using an SVG image for masking the corners and it did not work out very well due to antialiasing and lines falling between discrete pixels. It would be very difficult to get crisp enough lines with a scaled image whereas the drawn corner masks are guaranteed to be on whole pixel boundaries. A similar concept could certainly be used to mask the icon into a circle, polygon, or any other shape but I don't think those have enough mass appeal to integrate.

**Comment by idpaterson** [comment]
Could also get fancy with it and support multiple values for a `cornerRadius` option:

**`cornerRadius: true`**
Use a default radius for the icon type. For iOS that would be `20 / 114`, not sure if Android has a recommended corner radius or not.

**`cornerRadius: 20 / 114`**
If the cornerRadius is less than 1 treat it as a ratio as described above.

**`cornerRadius: 20`**
If the cornerRadius is greater than 1 treat it as a radius for the smallest icon size for the type, then scale up for larger icons. This behavior might be a bit confusing.

**`cornerRadius: function(type, width)`**
Allow the radius to be specified for every image based on the icon type and width, for people who want or need that much control. I think this one is overkill.

Given those options, my vote would be to stick with just ratios and support only the `cornerRadius: 20 / 114` and `cornerRadius: true` formats.

**Comment by carlcraig** [comment]
I think ratios is a good idea. So `true` or `20/114` should be enough configuration.

The other options could be nice to have too, depending on how much work would be involved.

The `true` option is really cool as it gives a quick way to get rounded corners without configuration.

Great ideas here. :+1:
